project:
  type: website
  output-dir: docs
  
website:
  title: "Phenological Shifts in the Ruby-Throated Hummingbird and the Cardinal Flower"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2025, Aubrey Monaco"

format:
  html:
    theme: morph
    toc: true

editor: source

