project:
  type: website
  output-dir: docs
  
website:
  title: "Pollination Pals: The Ruby-Throated Hummingbird and Cardinal Flower"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2025, Aubrey Monaco"

format:
  html:
    theme: morph
    toc: true

editor: source

